//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramTakmicenja.StraniceTakmicenja.Kategorije
{


    public partial class Juniori
    {

        /// <summary>
        /// lblFilterEkipaJun control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblFilterEkipaJun;

        /// <summary>
        /// ddlFilterEkipaJun control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterEkipaJun;

        /// <summary>
        /// pnlStatisticsJun control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlStatisticsJun;

        /// <summary>
        /// lblPocetniBodoviJuniori control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblPocetniBodoviJuniori;

        /// <summary>
        /// lblSrednjaVrednostJunioriPrepreke control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSrednjaVrednostJunioriPrepreke;

        /// <summary>
        /// lblSrednjaVrednostJunioriStafeta control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSrednjaVrednostJunioriStafeta;

        /// <summary>
        /// lblUkupanPlasmanJuniori control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblUkupanPlasmanJuniori;

        /// <summary>
        /// lblZbirGresakaJunioriPrepreke control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblZbirGresakaJunioriPrepreke;

        /// <summary>
        /// lblZbirGresakaStafetaJuniori control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblZbirGresakaStafetaJuniori;

        /// <summary>
        /// pnlPrepreke control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlPrepreke;

        /// <summary>
        /// VremePrepreke_Sudija1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox VremePrepreke_Sudija1;

        /// <summary>
        /// VremePrepreke_Sudija2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox VremePrepreke_Sudija2;

        /// <summary>
        /// VremePrepreke_Sudija3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox VremePrepreke_Sudija3;

        /// <summary>
        /// VremePrepreke_Sudija4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox VremePrepreke_Sudija4;

        /// <summary>
        /// VremePrepreke_Sudija5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox VremePrepreke_Sudija5;

        /// <summary>
        /// VremePrepreke_GlavniSudija control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox VremePrepreke_GlavniSudija;

        /// <summary>
        /// Greska2_Prep_Sudija1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska2_Prep_Sudija1;

        /// <summary>
        /// Greska2_Prep_Sudija2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska2_Prep_Sudija2;

        /// <summary>
        /// Greska2_Prep_Sudija3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska2_Prep_Sudija3;

        /// <summary>
        /// Greska2_Prep_Sudija4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska2_Prep_Sudija4;

        /// <summary>
        /// Greska2_Prep_Sudija5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska2_Prep_Sudija5;

        /// <summary>
        /// Greska2_Prep_GlavniSudija control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska2_Prep_GlavniSudija;

        /// <summary>
        /// Greska3_Prep_Sudija1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska3_Prep_Sudija1;

        /// <summary>
        /// Greska3_Prep_Sudija2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska3_Prep_Sudija2;

        /// <summary>
        /// Greska3_Prep_Sudija3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska3_Prep_Sudija3;

        /// <summary>
        /// Greska3_Prep_Sudija4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska3_Prep_Sudija4;

        /// <summary>
        /// Greska3_Prep_Sudija5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska3_Prep_Sudija5;

        /// <summary>
        /// Greska3_Prep_GlavniSudija control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska3_Prep_GlavniSudija;

        /// <summary>
        /// Greska4_Prep_Sudija1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska4_Prep_Sudija1;

        /// <summary>
        /// Greska4_Prep_Sudija2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska4_Prep_Sudija2;

        /// <summary>
        /// Greska4_Prep_Sudija3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska4_Prep_Sudija3;

        /// <summary>
        /// Greska4_Prep_Sudija4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska4_Prep_Sudija4;

        /// <summary>
        /// Greska4_Prep_Sudija5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska4_Prep_Sudija5;

        /// <summary>
        /// Greska4_Prep_GlavniSudija control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska4_Prep_GlavniSudija;

        /// <summary>
        /// Greska5_Prep_Sudija1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska5_Prep_Sudija1;

        /// <summary>
        /// Greska5_Prep_Sudija2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska5_Prep_Sudija2;

        /// <summary>
        /// Greska5_Prep_Sudija3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska5_Prep_Sudija3;

        /// <summary>
        /// Greska5_Prep_Sudija4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska5_Prep_Sudija4;

        /// <summary>
        /// Greska5_Prep_Sudija5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska5_Prep_Sudija5;

        /// <summary>
        /// Greska5_Prep_GlavniSudija control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska5_Prep_GlavniSudija;

        /// <summary>
        /// Greska6_Prep_Sudija1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska6_Prep_Sudija1;

        /// <summary>
        /// Greska6_Prep_Sudija2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska6_Prep_Sudija2;

        /// <summary>
        /// Greska6_Prep_Sudija3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska6_Prep_Sudija3;

        /// <summary>
        /// Greska6_Prep_Sudija4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska6_Prep_Sudija4;

        /// <summary>
        /// Greska6_Prep_Sudija5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska6_Prep_Sudija5;

        /// <summary>
        /// Greska6_Prep_GlavniSudija control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska6_Prep_GlavniSudija;

        /// <summary>
        /// Greska7_Prep_Sudija1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska7_Prep_Sudija1;

        /// <summary>
        /// Greska7_Prep_Sudija2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska7_Prep_Sudija2;

        /// <summary>
        /// Greska7_Prep_Sudija3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska7_Prep_Sudija3;

        /// <summary>
        /// Greska7_Prep_Sudija4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska7_Prep_Sudija4;

        /// <summary>
        /// Greska7_Prep_Sudija5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska7_Prep_Sudija5;

        /// <summary>
        /// Greska7_Prep_GlavniSudija control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska7_Prep_GlavniSudija;

        /// <summary>
        /// Greska8_Prep_Sudija1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska8_Prep_Sudija1;

        /// <summary>
        /// Greska8_Prep_Sudija2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska8_Prep_Sudija2;

        /// <summary>
        /// Greska8_Prep_Sudija3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska8_Prep_Sudija3;

        /// <summary>
        /// Greska8_Prep_Sudija4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska8_Prep_Sudija4;

        /// <summary>
        /// Greska8_Prep_Sudija5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska8_Prep_Sudija5;

        /// <summary>
        /// Greska8_Prep_GlavniSudija control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska8_Prep_GlavniSudija;

        /// <summary>
        /// Greska9_Prep_Sudija1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska9_Prep_Sudija1;

        /// <summary>
        /// Greska9_Prep_Sudija2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska9_Prep_Sudija2;

        /// <summary>
        /// Greska9_Prep_Sudija3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska9_Prep_Sudija3;

        /// <summary>
        /// Greska9_Prep_Sudija4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska9_Prep_Sudija4;

        /// <summary>
        /// Greska9_Prep_Sudija5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska9_Prep_Sudija5;

        /// <summary>
        /// Greska9_Prep_GlavniSudija control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska9_Prep_GlavniSudija;

        /// <summary>
        /// Greska10_Prep_Sudija1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska10_Prep_Sudija1;

        /// <summary>
        /// Greska10_Prep_Sudija2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska10_Prep_Sudija2;

        /// <summary>
        /// Greska10_Prep_Sudija3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska10_Prep_Sudija3;

        /// <summary>
        /// Greska10_Prep_Sudija4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska10_Prep_Sudija4;

        /// <summary>
        /// Greska10_Prep_Sudija5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska10_Prep_Sudija5;

        /// <summary>
        /// Greska10_Prep_GlavniSudija control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska10_Prep_GlavniSudija;

        /// <summary>
        /// Greska11_Prep_Sudija1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska11_Prep_Sudija1;

        /// <summary>
        /// Greska11_Prep_Sudija2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska11_Prep_Sudija2;

        /// <summary>
        /// Greska11_Prep_Sudija3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska11_Prep_Sudija3;

        /// <summary>
        /// Greska11_Prep_Sudija4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska11_Prep_Sudija4;

        /// <summary>
        /// Greska11_Prep_Sudija5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska11_Prep_Sudija5;

        /// <summary>
        /// Greska11_Prep_GlavniSudija control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska11_Prep_GlavniSudija;

        /// <summary>
        /// pnlStafeta control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlStafeta;

        /// <summary>
        /// VremeStafete_Starter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox VremeStafete_Starter;

        /// <summary>
        /// VremeStafete_Merilac1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox VremeStafete_Merilac1;

        /// <summary>
        /// VremeStafete_Merilac2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox VremeStafete_Merilac2;

        /// <summary>
        /// VremeStafete_StazniSudija control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox VremeStafete_StazniSudija;

        /// <summary>
        /// VremeStafete_GlavniSudija control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox VremeStafete_GlavniSudija;

        /// <summary>
        /// Greska2_Stafeta_Starter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska2_Stafeta_Starter;

        /// <summary>
        /// Greska2_Stafeta_Merilac1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska2_Stafeta_Merilac1;

        /// <summary>
        /// Greska2_Stafeta_Merilac2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska2_Stafeta_Merilac2;

        /// <summary>
        /// Greska2_Stafeta_StazniSudija control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska2_Stafeta_StazniSudija;

        /// <summary>
        /// Greska2_Stafeta_GlavniSudija control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska2_Stafeta_GlavniSudija;

        /// <summary>
        /// Greska3_Stafeta_Starter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska3_Stafeta_Starter;

        /// <summary>
        /// Greska3_Stafeta_Merilac1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska3_Stafeta_Merilac1;

        /// <summary>
        /// Greska3_Stafeta_Merilac2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska3_Stafeta_Merilac2;

        /// <summary>
        /// Greska3_Stafeta_StazniSudija control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska3_Stafeta_StazniSudija;

        /// <summary>
        /// Greska3_Stafeta_GlavniSudija control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska3_Stafeta_GlavniSudija;

        /// <summary>
        /// Greska4_Stafeta_Starter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska4_Stafeta_Starter;

        /// <summary>
        /// Greska4_Stafeta_Merilac1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska4_Stafeta_Merilac1;

        /// <summary>
        /// Greska4_Stafeta_Merilac2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska4_Stafeta_Merilac2;

        /// <summary>
        /// Greska4_Stafeta_StazniSudija control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska4_Stafeta_StazniSudija;

        /// <summary>
        /// Greska4_Stafeta_GlavniSudija control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Greska4_Stafeta_GlavniSudija;

        /// <summary>
        /// btnSacuvaj control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSacuvaj;

        /// <summary>
        /// lblPoruka control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblPoruka;
    }
}
